### ISSUE TITLE
How to map validator node with wallet?

### ISSUE THREAD

**Issue by nampdn** [kardiachain/go-kardia#144]
Hi, I try to become a validator which is running full node. It's seem there's a way to register to become a candidate, do I need to running my own node when I was elected enough 12.5M KAI? Or it's just my identity on-chain without operating the node?

**Comment by trinhdn97** [comment]
Hi @nampdn ! First of all, you may need to start a node to sync up with KardiaChain mainnet, follow this document [README.md](https://github.com/kardiachain/go-kardia/blob/v1.1.0/deployment/mainnet/README.md) for more details.

In case you want nominate yourself as a validator, you need 25k KAI to register as a candidate first. After your candidate is staked more than 12.5m KAI, by yourself or your delegetors, with a running, updated fullnode, you will be eligible to start validating blocks and receive rewards. The private key of the owner address of your validator node can be configured at https://github.com/kardiachain/go-kardia/blob/v1.1.0/deployment/mainnet/kai_config.yaml#L22 in the node config file. That owner address is also your on-chain identity you mentioned. With their identity, validator owners are eligible for applying some changes to their owned validator node (such as starting to validate blocks, changing commission rate, validator name,...) or voting for KardiaChain network parameters changing proposals.

**Comment by nampdn** [comment]
Thanks, I generated my pair with nmemonic phrase, is there a library to derive the private key from it?

**Comment by trinhdn97** [comment]
If you simply want to derive one mnemonic phrase to a private key, you can get to https://wallet.kardiachain.io on KardiaChain explorer, access your wallet using your phrase, then there will be a lock icon below the address which contains the derived private key.

In case you want to derive a batch of phrases, you may need a BIP39 or BIP44 library to do so. KardiaChain network uses the same cryptographic mechanism as Ethereum, so that you can refer to similar issues on Ethereum to derive or generate KardiaChain addresses.

**Comment by nampdn** [comment]
Thank you!
